### ISSUE TITLE
Dont make this shit public

### ISSUE THREAD

**Issue by ItzBulkDev** [TheDiamondYT1/PocketUHC#1]
Luke are you mental? dont make this public

**Comment by TheDiamondYT1** [comment]
Haha im not gonna add loads of features judt the core ones.

**Comment by TheDiamondYT1** [comment]
There read the repo description now

**Comment by TheDiamondYT1** [comment]
There read the repo description now

**Comment by TheDiamondYT1** [comment]
There read the repo description now

**Comment by TheDiamondYT1** [comment]
There read the repo description now
